# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from centrality_controlplane_sdk.models.throughput import Throughput
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NetworkThroughputMeasurement(BaseModel):
    """
    A measurement of NetworkThroughput
    """ # noqa: E501
    vm_id: StrictStr
    ts: datetime
    per_interface: List[Throughput]
    total: Throughput
    __properties: ClassVar[List[str]] = ["vm_id", "ts", "per_interface", "total"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkThroughputMeasurement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in per_interface (list)
        _items = []
        if self.per_interface:
            for _item in self.per_interface:
                if _item:
                    _items.append(_item.to_dict())
            _dict['per_interface'] = _items
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NetworkThroughputMeasurement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vm_id": obj.get("vm_id"),
            "ts": obj.get("ts"),
            "per_interface": [Throughput.from_dict(_item) for _item in obj.get("per_interface")] if obj.get("per_interface") is not None else None,
            "total": Throughput.from_dict(obj.get("total")) if obj.get("total") is not None else None
        })
        return _obj


