# Dynamically add an agent container that talks to the control plane:
# docker run -it --rm --network centrality_default --name centrality-machineagent3 centrality-machineagent1 python3.11 machineagent/machineagent/cli.py launch -f tests/configs/dockercompose/machineagent-auto.yaml --machine-id auto
services:
  machineagent-auto:
    build: .
    deploy:
      replicas: 2
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 machineagent/machineagent/cli.py launch -f tests/configs/dockercompose/machineagent-auto.yaml --machine-id auto"
    depends_on:
      - controlplane

  machineagent-real:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 machineagent/machineagent/cli.py launch -f tests/configs/dockercompose/machineagent-real.yaml"
    depends_on:
      - controlplane

  machineagent-fake:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 machineagent/machineagent/cli.py launch -f tests/configs/dockercompose/machineagent-fake.yaml"
    depends_on:
      - controlplane

  machineagent-gpu:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 machineagent/machineagent/cli.py launch -f tests/configs/dockercompose/machineagent-gpus.yaml"
    depends_on:
      - controlplane

  controlplane:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality/controlplane
    command: "python3.11 controlplane/cli.py launch --postgres-host postgres"
    depends_on:
      - postgres

  rapidui:
    build: .
    ports:
      - "0.0.0.0:8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality/rapidui
    command: "./launch.bash ../tests/configs/dockercompose/rapidui.yaml"
    depends_on:
      - controlplane

  postgres:
    image: "postgres:16.1"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "0.0.0.0:5432:5432"