# Dynamically add an agent container that talks to the control plane:
# docker run -it --rm --network centrality_default --name centrality-vmagent3 centrality-vmagent1 python3.11 vmagent/vmagent/cli.py launch -f tests/configs/dockercompose/vmagent-auto.yaml --vm-id auto
services:
  vmagent-augo:
    build: .
    deploy:
      replicas: 1
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 vmagent/vmagent/cli.py launch -f tests/configs/dockercompose/vmagent-auto.yaml --vm-id auto"
    depends_on:
      - controlplane

  vmagent-manual:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 vmagent/vmagent/cli.py launch -f tests/configs/dockercompose/vmagent-manual.yaml"
    depends_on:
      - controlplane

  vmagent-many-cpus:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality
    command: "python3.11 vmagent/vmagent/cli.py launch -f tests/configs/dockercompose/vmagent-auto-many-cpus.yaml --vm-id many-cpus"
    depends_on:
      - controlplane

  controlplane:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /centrality/controlplane
    command: "python3.11 controlplane/cli.py launch --postgres-host postgres"
    depends_on:
      - postgres

  postgres:
    image: "postgres:16.1"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"