# Override docker compose to mount the code into the containers to skip building during development
# docker compose -f compose.yaml -f compose-override-mountcode.yaml up
version: '3'
services:
  machineagent-auto:
    volumes:
      - .:/centrality
  machineagent-real:
    volumes:
      - .:/centrality
  machineagent-fake:
    volumes:
      - .:/centrality
  machineagent-gpu:
    volumes:
      - .:/centrality
  controlplane:
    volumes:
      - .:/centrality
  rapidui:
    volumes:
      - .:/centrality