# fly.toml app configuration file generated for centrality-dev on 2023-12-14T03:50:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "centrality-dev"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["fastapi"]

[processes]
  fastapi = "python3.11 controlplane/controlplane/cli.py launch"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
