# fly.toml app configuration file generated for centrality-dev on 2023-12-14T03:50:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "centrality-dev"
primary_region = "iad"

[build]

[[services]]
  processes = ["fastapi"]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "8000"

[[services]]
  processes = ["streamlit"]
  internal_port = 8501
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"


[processes]
  fastapi = "python controlplane/controlplane/cli.py launch --postgres-host centrality-datastore-dev.flycast"
  streamlit = "make -C rapidui launch-fly"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  PYTHONUNBUFFERED = 1