[theme]
#primaryColor="#407ad6"
primaryColor="#3f7ad7"
backgroundColor="#1B2635"
#secondaryBackgroundColor="#407ad6"
#secondaryBackgroundColor="#233044"
#secondaryBackgroundColor="#1B2635"
secondaryBackgroundColor="#203d6b"

textColor="#FFFFFFF2"
font="sans serif"