# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist

class CpuMeasurement(BaseModel):
    """
    A single CPU measurement, with a list of CPU percents for each core  # noqa: E501
    """
    vm_id: StrictStr = Field(...)
    ts: datetime = Field(...)
    cpu_percents: conlist(Union[StrictFloat, StrictInt]) = Field(...)
    __properties = ["vm_id", "ts", "cpu_percents"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CpuMeasurement:
        """Create an instance of CpuMeasurement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CpuMeasurement:
        """Create an instance of CpuMeasurement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CpuMeasurement.parse_obj(obj)

        _obj = CpuMeasurement.parse_obj({
            "vm_id": obj.get("vm_id"),
            "ts": obj.get("ts"),
            "cpu_percents": obj.get("cpu_percents")
        })
        return _obj


