# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from centrality_controlplane_sdk.models.machine_info import MachineInfo

class TestMachineInfo(unittest.TestCase):
    """MachineInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MachineInfo:
        """Test MachineInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MachineInfo`
        """
        model = MachineInfo()
        if include_optional:
            return MachineInfo(
                machine_id = '',
                last_heartbeat_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                registration_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                num_cpus = 56,
                cpu_description = '',
                host_memory_mb = 56,
                num_gpus = 56,
                gpu_type = '',
                gpu_memory_mb = 56,
                nvidia_driver_version = '',
                hostname = ''
            )
        else:
            return MachineInfo(
                machine_id = '',
                last_heartbeat_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                registration_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                num_cpus = 56,
                cpu_description = '',
                host_memory_mb = 56,
                num_gpus = 56,
                gpu_type = '',
                gpu_memory_mb = 56,
                nvidia_driver_version = '',
                hostname = '',
        )
        """

    def testMachineInfo(self):
        """Test MachineInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
