# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from centrality_controlplane_sdk.models.nvidia_smi_measurement import NvidiaSmiMeasurement

class TestNvidiaSmiMeasurement(unittest.TestCase):
    """NvidiaSmiMeasurement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NvidiaSmiMeasurement:
        """Test NvidiaSmiMeasurement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NvidiaSmiMeasurement`
        """
        model = NvidiaSmiMeasurement()
        if include_optional:
            return NvidiaSmiMeasurement(
                machine_id = '',
                ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                output = ''
            )
        else:
            return NvidiaSmiMeasurement(
                machine_id = '',
                ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                output = '',
        )
        """

    def testNvidiaSmiMeasurement(self):
        """Test NvidiaSmiMeasurement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
