# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from controlplane_sdk.api.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataApi()

    def tearDown(self) -> None:
        pass

    def test_get_auth_healthcheck(self) -> None:
        """Test case for get_auth_healthcheck

        Get Auth Healthcheck
        """
        pass

    def test_get_cpu_metric(self) -> None:
        """Test case for get_cpu_metric

        Get Cpu Metric
        """
        pass

    def test_get_healthcheck(self) -> None:
        """Test case for get_healthcheck

        Get Healthcheck
        """
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        Get Info
        """
        pass

    def test_get_latest_cpu_measurements(self) -> None:
        """Test case for get_latest_cpu_measurements

        Get Latest Cpu Measurements
        """
        pass

    def test_list_vms(self) -> None:
        """Test case for list_vms

        List Vms
        """
        pass

    def test_put_cpu_metric(self) -> None:
        """Test case for put_cpu_metric

        Put Cpu Metric
        """
        pass

    def test_report_heartbeat(self) -> None:
        """Test case for report_heartbeat

        Report Heartbeat
        """
        pass


if __name__ == '__main__':
    unittest.main()
