# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from centrality_controlplane_sdk.models.gpu_memory import GpuMemory

class TestGpuMemory(unittest.TestCase):
    """GpuMemory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GpuMemory:
        """Test GpuMemory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GpuMemory`
        """
        model = GpuMemory()
        if include_optional:
            return GpuMemory(
                used_mb = 1.337,
                total_mb = 1.337
            )
        else:
            return GpuMemory(
                used_mb = 1.337,
                total_mb = 1.337,
        )
        """

    def testGpuMemory(self):
        """Test GpuMemory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
