# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from centrality_controlplane_sdk.models.vm_registration_info import VmRegistrationInfo

class TestVmRegistrationInfo(unittest.TestCase):
    """VmRegistrationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VmRegistrationInfo:
        """Test VmRegistrationInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VmRegistrationInfo`
        """
        model = VmRegistrationInfo()
        if include_optional:
            return VmRegistrationInfo(
                num_cpus = 56,
                cpu_description = '',
                host_memory_mb = 56,
                num_gpus = 56,
                gpu_type = '',
                gpu_memory_mb = 56,
                hostname = ''
            )
        else:
            return VmRegistrationInfo(
                num_cpus = 56,
                cpu_description = '',
                host_memory_mb = 56,
                num_gpus = 56,
                gpu_type = '',
                gpu_memory_mb = 56,
                hostname = '',
        )
        """

    def testVmRegistrationInfo(self):
        """Test VmRegistrationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
