# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from centrality_controlplane_sdk.models.disk_throughput import DiskThroughput

class TestDiskThroughput(unittest.TestCase):
    """DiskThroughput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiskThroughput:
        """Test DiskThroughput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiskThroughput`
        """
        model = DiskThroughput()
        if include_optional:
            return DiskThroughput(
                disk_name = '',
                read_mbps = 1.337,
                write_mbps = 1.337
            )
        else:
            return DiskThroughput(
                disk_name = '',
                read_mbps = 1.337,
                write_mbps = 1.337,
        )
        """

    def testDiskThroughput(self):
        """Test DiskThroughput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
