# coding: utf-8

"""
    centrality-controlplane

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_auth_healthcheck_healthz_auth_get(self) -> None:
        """Test case for get_auth_healthcheck_healthz_auth_get

        Get Auth Healthcheck  # noqa: E501
        """
        pass

    def test_get_cpu_metric_metrics_cpu_get(self) -> None:
        """Test case for get_cpu_metric_metrics_cpu_get

        Get Cpu Metric  # noqa: E501
        """
        pass

    def test_get_healthcheck_healthz_get(self) -> None:
        """Test case for get_healthcheck_healthz_get

        Get Healthcheck  # noqa: E501
        """
        pass

    def test_put_cpu_metric_metrics_cpu_post(self) -> None:
        """Test case for put_cpu_metric_metrics_cpu_post

        Put Cpu Metric  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
