name: Lint and format
on: [push]
jobs:
  lint-and-format-all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies including dev
        run: make install-dev

      - name: Run format checker
        run: make formatcheck

      - name: Run linter
        run: make lint
          
